version: "3.8"

networks:
    monitor:
        driver: bridge

services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        hostname: prometheus
        restart: always
        volumes:
            - ${VOLUMES_CONFIG}prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - ${VOLUMES_CONFIG}node_down.yml:/etc/prometheus/node_down.yml:ro
        ports:
            - "9091:9090"
        networks:
            - ${NETWORKS}

    node-exporter:
        image: quay.io/prometheus/node-exporter:latest
        container_name: node-exporter
        hostname: node-exporter
        restart: always
        ports:
            - "9101:9100"
        networks:
            - ${NETWORKS}

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        container_name: cadvisor
        hostname: cadvisor
        restart: always
        volumes:
            - /:/rootfs:ro
            - /var/run/docker.sock:/var/run/docker.sock:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        cgroup_parent: system.slice
        ports:
          - "8081:8080"
        networks:
          - ${NETWORKS}

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        hostname: grafana
        restart: always
        ports:
            - "3001:3000"
        environment:
          - GF_SERVER_DOMAIN=localhost:3000
          - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
          - GF_LOG_FILTERS="debug"
          - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
          - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
        networks:
            - ${NETWORKS}
