global:
  smtp_smarthost: 'smtp.163.com: 25' # 163 сервер
  smtp_from: 'siyuetian@163.com '# Адрес электронной почты
  smtp_auth_username: 'tsiyuetian@163.com '# Имя пользователя электронной почты, отправившего письмо, которое является вашим адресом электронной почты
  smtp_auth_password: 'TPP ***' # Пароль электронной почты для отправки электронной почты
  smtp_require_tls: false # Не выполнять проверку tls
 
route:
   group_by: ['alertname']
   group_wait: 10s
   group_interval: 10s
   repeat_interval: 10m
   receiver: live-monitoring
 
receivers:
  - name: 'live-monitoring'
    email_configs:
      - to: '404kastrulkanotfound@gmail.com' # Адрес электронной почты


